services:
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: DockerFile.api-gateway
    ports:
      - "8080:8080"
    networks:
      - routing-network

  router-service:
    build: 
      context: ./router-service
      dockerfile: DockerFile.router-service
    ports:
      - "8081:8081"
    networks:
      - routing-network

  connection-service:
    build: 
      context: ./connection-service
      dockerfile: DockerFile.connection-service
    ports:
      - "8082:8082"
    networks:
      - routing-network

  discovery-service:
    build: 
      context: ./discovery-service
      dockerfile: DockerFile.discovery-service
    ports:
      - "8083:8083"
    networks:
      - routing-network

networks:
  routing-network:
    driver: bridge
